### ISSUE TITLE
Obscure error message when user forgets to add parentheses.

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [plangrid/flask-rebar#115]
A simple parentheses omission in schema instantiation like below (see the comment in the `request_body_schema` line) can cause a gnarly swagger generation error message:

Code:
```
from marshmallow import Schema
from flask_rebar import Rebar

class MySchema(Schema):
    ...

rebar = Rebar()
registry = rebar.create_handler_register(...)
@registry.handles(
    rule='/endpoint',
    method='POST',
    request_body_schema=MySchema   # Should be MySchema()
):
    ...
```

Error message:
flask_rebar.swagger_generation.marshmallow_to_swagger.UnregisteredType: No registered type found in method resolution order: (<class 'marshmallow.schema.SchemaMeta'>, <class 'type'>, <class 'object'>)
Registered types: [<class 'marshmallow.fields.Boolean'>, <class 'marshmallow.fields.
Date'>, ...]

I spent ~30 minutes debugging a similar error in my app. It would be great if rebar could suggest to the user to check if they missed any parentheses.

**Comment by barakalon** [comment]
Instead of throwing a better error message, what if we just go ahead and instantiate it?

We have this function, `normalize_schema`: https://github.com/plangrid/flask-rebar/blob/f435e5eec82d98d48b6d9b567ef5168292e2a59a/flask_rebar/utils/request_utils.py#L90

**Comment by RookieRick** [comment]
I'm slightly torn on whether to detect this case (where we get a Type as schema and the name matches a schema we do know) and raise a more informative warning, or as Barak suggests detect and infer the intent.  
I like the user-friendliness of the "just go ahead and instantiate it" approach; only thing that gives me a slight case of the heebie-jeebies on that is that we're masking a developer's error; which, I suppose could argue for:
1. Go ahead and instantiate it for them, and
2: Raise a warning rather than an error

**Comment by Sytten** [comment]
I am in favor for instantiating if we pass a class. But it could still happen that the user passes garbage in the field so I think it would be great if we had a better error message too.
