### ISSUE TITLE
Support for marshmallow_sqlalchemy?

### ISSUE THREAD

**Issue by lidavidm** [plangrid/flask-rebar#150]
We've been using flask-rebar with [marshmallow_sqlalchemy](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/) and ran into an issue: right now, flask-rebar doesn't understand the [custom field types](https://marshmallow-sqlalchemy.readthedocs.io/en/latest/api_reference.html#module-marshmallow_sqlalchemy.fields) that marshmallow_sqlalchemy adds, raising an `UnregisteredType` exception. 

I see there's [support](https://flask-rebar.readthedocs.io/en/latest/quickstart/swagger_generation.html#extending-swagger-generation) for registering more Swagger converters. We're considering implementing these, but wanted to check: could they belong as an (optional?) component of this project, or should we factor them out into a third project? Additionally, we're curious how you or others do handle using Rebar with Marshmallow and SQLAlchemy (if this combination is used at all), or if we could be putting together things differently.

**Comment by Sytten** [comment]
The way flask-rebar usually works is by third-party plugins when possible. In your case it is possible since the registration can be done at runtime if I am not mistaken. If you do that, please share it on Pypi so we can link to it for other devs to use. 

If I understand you correctly, the base function of `marshmallow_sqlalchemy` works (aka you can query your api) but you can't check the swagger? I am a bit confused. I have a done quite a big project (20k+ LOC) with both no problem, but I never used `marshmallow_sqlalchemy`, I used plain sqlalchemy models and plain marshmallow schemas.

**Comment by lidavidm** [comment]
Yes, we can do it at runtime, was just wondering if you felt such plugins should go here or elsewhere. If we do open-source it, I'll definitely follow up here so we can link it!

Yes, the base function works - however, generation of Swagger JSON fails because rebar can't find a converter for the custom types that `marshmallow_sqlalchemy` uses. If you don't use these types (e.g. a foreign key reference to another table), then everything works fine.

**Comment by Sytten** [comment]
Ok I understand better now. It would definitely be awesome if you could write that plugin! I don't think anyone on the "core" team has the time to do it, but it should be straight forward. If you need help don't hesitate to poke someone. I think @airstandley has the most experience with this converter, but since I reviewed the code too I also have a good idea.

**Comment by lidavidm** [comment]
Thanks for the help :) We actually discussed a bit more and decided it would be better to recommend using separate objects for database and API to our partner teams; so for now we won't write the converters (also, it raises questions like whether a relationship works by embedding a link, an ID, or the entire object...) We've been happy with Rebar itself though!

**Comment by airstandley** [comment]
I have messed around with using marshmallow_sqlalchemy on a small service, but never used any of the custom_field_types. I think Swagger converters for those fields would definitely work as a plugin if the need arises.

Glad you've had a good experience with Rebar!
