### ISSUE TITLE
BUG: DEPRECATED WERKZEUG METHOD

### ISSUE THREAD

**Issue by pirrofra** [plangrid/flask-rebar#265]
File "/usr/local/lib/python3.8/site-packages/flask_rebar/__init__.py", line 5, in <module>
    from flask_rebar.rebar import (
  File "/usr/local/lib/python3.8/site-packages/flask_rebar/rebar.py", line 26, in <module>
    from flask_rebar.authenticators import Authenticator
  File "/usr/local/lib/python3.8/site-packages/flask_rebar/authenticators/__init__.py", line 3, in <module>
    from flask_rebar.authenticators.header_api_key import HeaderApiKeyAuthenticator
  File "/usr/local/lib/python3.8/site-packages/flask_rebar/authenticators/header_api_key.py", line 11, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/usr/local/lib/python3.8/site-packages/werkzeug/security.py)

safe_str_cmp has been removed in the lastest version of werkzeug (https://werkzeug.palletsprojects.com/en/2.1.x/changes/)

**Comment by staccastacca** [comment]
Up

**Comment by RookieRick** [comment]
OOF, thanks for the report - will get a patch out ASAP

**Comment by RookieRick** [comment]
Update: ran into some other dependency issues in the process; I need to think a bit and possibly consult with other team members in the morning so will plan to release patch tomorrow morning. In meantime, I'd suggest just pinning to werkzeug < 2.1.0 to avoid breaking change and we'll work to resolve so that won't be necessary. Thanks again, and stay tuned

**Comment by RookieRick** [comment]
OK, thanks for your patience folks. 2.1.2 is out now and should address this (by pinning `werkzeug`).
Hot on its heels should be 2.2.0 in which I'll remove any uses of stuff that was removed in `werkzeug 2.1.0`
