### ISSUE TITLE
Rename marshal_schema to response_body_schema

### ISSUE THREAD

**Issue by jab** [plangrid/flask-rebar#89]
To better match `request_body_schema`. (First deprecate but continue to support `marshal_schema` as an alias of `response_body_schema` until Rebar v2.)

**Comment by barakalon** [comment]
I agree - "response_body_schema" is clearer and more consistent.

**Comment by RookieRick** [comment]
Agreed x2 - I've got a ticket assigned to myself for this one internally now

**Comment by jab** [comment]
Sweet, thanks @rookierick! Teaching a class to a fresh crop of new Flask-Rebar users tomorrow morning. On the off chance you were thinking of doing a release today, I’ll upgrade so the students will find Rebar that much easier!

**Comment by RookieRick** [comment]
> Sweet, thanks @RookieRick! Teaching a class to a fresh crop of new Flask-Rebar users tomorrow morning. On the off chance you were thinking of doing a release today, I’ll upgrade so the students will find Rebar that much easier!

I'll plan to cut a release this evening -- @jab, in case you happen to be monitoring GitHub between now and then..  preference question for you as you're looking to use it tomorrow, will it make your life harder if it's a "release candidate" version (1.7.1-rc.1 as opposed to just 1.7.1)?  This seems like as good a time as any for us to kick the tires on adding a little cushion to our release process per the recent suggestion from @barakalon (https://github.com/plangrid/flask-rebar/pull/93#pullrequestreview-235701467) but if that will complicate things for you in prepping for tomorrow's teachings I can just roll with 1.7.1 for today and try out the "rc" approach for the next one :D

**Comment by jab** [comment]
Thanks @RookieRick, much appreciate your asking! If 1.7.1 would be doable, that’ll make things smoother on our end, but either way I’ll keep an eye out and try to update once it’s out. thanks again!

**Comment by RookieRick** [comment]
Sounds good.  We've survived this long without formal rc's, I imagine the world won't end. 🤣   Minor (pun somewhat intended) tweak since I am technically deprecating - albeit not removing yet - stuff; my tortured reading of semantic versioning guide has me considering this a minor vs patch release, so be on the lookout for 1.8.0 later today

**Comment by RookieRick** [comment]
Also, in case you haven't yet run across it, looks like I introduced a subtle bug in my deprecation handler..   Patch forthcoming.  And egg on my face for the "world won't end" comment above 😝

**Comment by jab** [comment]
Sorry if you released 1.8.0 earlier than you wanted to because of me! Glad you caught the bug so fast. I’ll upgrade us to 1:8.1 once it’s out. FWIW, it was great to be able to teach the class yesterday with `response_body_schema` right next to `request_body_schema`  I think this latest crop of students got the hang of Flask-Rebar faster than previous ones thanks to this change. Thanks again!

**Comment by RookieRick** [comment]
Haha no worries!  
This actually points out the importance of me doing a little more legwork to institute some level of smoke testing in tandem with the transition to using release candidates, because just doing an RC prob wouldn't have caught this one anyway.  Great to hear that it went well with your class!  When I got the internal bug report on this one this afternoon I was a little terrified that I might have set you up for disaster 🤣
